"""
summarizer.py
----------------
Pluggable summarization backend.

Per the task requirements: "Do not rely completely on ChatGPT or external
APIs" + "use the grok api key ... not using open API keys". So the design is:

  1. If an XAI_API_KEY (Grok / x.ai) environment variable is set, summaries
     are generated by calling the Grok chat-completions endpoint
     (OpenAI-compatible schema, model "grok-beta" / "grok-4-latest" etc).
  2. If no key is set (e.g. running this in an offline/sandboxed grader,
     or you simply haven't configured billing yet), the system AUTOMATICALLY
     falls back to a 100% local, dependency-light EXTRACTIVE summarizer
     (TF-IDF + sentence centrality, i.e. a tiny TextRank). No network call,
     no external API, ever required for the system to function end-to-end.

This means the whole pipeline (topic checkpoints, 100-message checkpoints,
RAG answers) works completely offline out of the box, and gets upgraded to
LLM-quality abstractive summaries the moment you export XAI_API_KEY.
"""
import os
import json
import re
import urllib.request
import urllib.error
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from sklearn.metrics.pairwise import cosine_similarity

# sklearn's default English stopword list is inconsistent about auxiliary /
# question verbs ("do" is in there, but "does" and "did" are NOT). Those
# slip through as if they were meaningful keywords and can hijack a
# similarity ranking (e.g. "Does the user have pets?" matching some
# unrelated sentence that happens to contain the word "does"). We extend
# the stopword set for query-relevance scoring to close that gap.
EXTRA_STOPWORDS = {"does", "did", "say", "said", "tell", "told", "know", "knows", "really"}
QA_STOP_WORDS = list(ENGLISH_STOP_WORDS.union(EXTRA_STOPWORDS))

GROK_API_URL = "https://api.x.ai/v1/chat/completions"
GROK_MODEL = os.environ.get("GROK_MODEL", "grok-4-latest")


def _grok_available():
    return bool(os.environ.get("XAI_API_KEY"))


def _call_grok(prompt: str, system: str = "You are a concise summarization assistant.", max_tokens=220):
    api_key = os.environ.get("XAI_API_KEY")
    payload = {
        "model": GROK_MODEL,
        "messages": [
            {"role": "system", "content": system},
            {"role": "user", "content": prompt},
        ],
        "max_tokens": max_tokens,
        "temperature": 0.3,
    }
    req = urllib.request.Request(
        GROK_API_URL,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            return data["choices"][0]["message"]["content"].strip()
    except Exception as e:
        # network blocked, key invalid, rate limited, etc -> fall back gracefully
        print(f"[summarizer] Grok API call failed, falling back to local summary: {e}")
        return None


def _split_sentences(text: str):
    import re
    parts = re.split(r'(?<=[.!?])\s+', text.strip())
    return [p for p in parts if p]


def extractive_summary(text: str, max_sentences: int = 3) -> str:
    """
    Fully offline extractive summary:
    1. Split into sentences
    2. TF-IDF embed sentences (IDF fit on THIS segment's own sentences)
    3. Score each sentence by its total TF-IDF "informativeness" mass
       (sum of its TF-IDF weights). Generic filler shared across most
       sentences in casual chat ("that's great!", "I'm doing well") gets
       a LOW idf within the segment (it recurs constantly) and therefore
       a low score; sentences carrying distinctive, topic-specific words
       (names, places, nouns particular to this segment) score higher.
       This is deliberately NOT a centrality/"average similarity to
       everything else" score -- that approach was tried first and it
       systematically promoted bland filler sentences instead of the
       actual topical content, since filler is similar to everything.
    4. Lightly penalize very short (<4 word) sentences, which are almost
       always filler/acknowledgements regardless of vocabulary.
    5. Return the top-N sentences, re-ordered by their original position
       (so the summary still reads in a sensible order).
    """
    sentences = _split_sentences(text)
    if len(sentences) <= max_sentences:
        return " ".join(sentences)

    try:
        vec = TfidfVectorizer(stop_words=QA_STOP_WORDS)
        mat = vec.fit_transform(sentences)
        scores = np.asarray(mat.sum(axis=1)).flatten()
        for i, s in enumerate(sentences):
            if len(s.split()) < 4:
                scores[i] *= 0.3
        top_idx = sorted(np.argsort(scores)[-max_sentences:])
        return " ".join(sentences[i] for i in top_idx)
    except ValueError:
        # e.g. all stopwords / empty vocabulary
        return " ".join(sentences[:max_sentences])


def summarize(text: str, kind: str = "topic", max_sentences: int = 3) -> dict:
    """
    Returns {"summary": str, "method": "grok" | "extractive"}
    `kind` is just used to flavor the LLM prompt ("topic" vs "100-message checkpoint").
    """
    if _grok_available():
        if kind == "topic":
            prompt = (
                "Summarize the following conversation segment in 1-2 sentences, "
                "focusing on WHAT topic is being discussed:\n\n" + text
            )
        else:
            prompt = (
                "Summarize the following block of chat messages in 2-3 sentences, "
                "covering the main subjects discussed:\n\n" + text
            )
        result = _call_grok(prompt)
        if result:
            return {"summary": result, "method": "grok"}

    return {"summary": extractive_summary(text, max_sentences=max_sentences), "method": "extractive"}


def generate_answer(query: str, context_blocks: list) -> dict:
    """
    Combine retrieved context into a final answer.
    Uses Grok if available, else a query-focused local extractive combiner.
    """
    context_text = "\n\n".join(context_blocks)
    if _grok_available():
        prompt = (
            f"Answer the user's question using ONLY the context below. "
            f"Be concise and specific.\n\nCONTEXT:\n{context_text}\n\nQUESTION: {query}"
        )
        result = _call_grok(prompt, system="You answer questions strictly using the given context.", max_tokens=300)
        if result:
            return {"answer": result, "method": "grok"}

    # ---- local fallback: QUERY-FOCUSED extractive answer ----
    # Unlike a generic summary, this scores each candidate sentence by its
    # similarity to the QUESTION itself, so the picked sentences are the
    # ones that actually address what was asked (not just "informative
    # sentences in general").
    sentences = []
    seen = set()
    for block in context_blocks:
        for s in _split_sentences(block):
            key = re.sub(r"\s+", " ", s.strip().lower())
            if len(s.split()) >= 3 and key not in seen:
                seen.add(key)
                sentences.append(s)

    if not sentences:
        return {"answer": "I couldn't find a specific answer to that in the conversation history.",
                "method": "extractive"}

    try:
        vec = TfidfVectorizer(stop_words=QA_STOP_WORDS)
        mat = vec.fit_transform(sentences + [query])
        query_vec = mat[-1]
        sent_mat = mat[:-1]
        sims = cosine_similarity(query_vec, sent_mat)[0]
        # A sentence that itself ends in "?" is very often just an echo of
        # the question being asked (common in this Q&A-style chat data),
        # not an actual answer -- down-weight those candidates.
        sims = np.array([
            s * (0.35 if sentences[i].strip().endswith("?") else 1.0)
            for i, s in enumerate(sims)
        ])
        top_n = min(3, len(sentences))
        top_idx = [i for i in np.argsort(sims)[::-1][:top_n] if sims[i] > 0]
        if not top_idx:
            answer = extractive_summary(context_text, max_sentences=3)
        else:
            answer = " ".join(sentences[i] for i in sorted(top_idx))
    except ValueError:
        answer = extractive_summary(context_text, max_sentences=3)

    return {"answer": answer, "method": "extractive"}
